name: Hello World Workflow


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"
